- name: Install required utilities
  become: yes
  apt:
    name:
      - python3-devel
      - gcc
      - git
      - ansible
      - apt-utils
      - libffi-dev
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Install pip
  become: yes
  yum:
    name: python3-pip
    state: present

- name: Create directory for docker config
  become: yes
  file:
    path: /etc/docker/
    state: directory
  when: docker_config is defined and docker_config

- name: Create docker config
  become: yes
  copy:
    content: "{{ docker_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
  when: docker_config is defined and docker_config

- name: Add Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add docker-ce repository
  become: yes
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Install docker
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

- name: Start docker daemon
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  become: yes
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: install docker and docker-compose for python
  pip:
    name:
      - docker-py
      - docker-compose
    state: present
    extra_args: --user
