---
- name: Install required utilities
  become: yes
  apt:
    name:
      - lvm2
      - git
      - python3.6
      - epel-release
    state: present

- name: Install pip
  become: yes
  apt:
    name: python3-pip
    state: present

- name: Update python dependencies
  become: yes
  pip:
    name:
      - setuptools
      - requests
    state: forcereinstall

- name: Fetch devstack
  git:
    repo: "https://opendev.org/openstack/devstack.git"
    dest: ~/devstack
    version: "{{ openstack_branch }}"
    accept_hostkey: yes
    force: yes
