---
- name: Get vrouter docker name
  become: yes
  shell: |
    docker ps --filter "label=net.juniper.contrail.container.name=contrail-vrouter-agent" --format {{' "{{.Names}}" '}}
  changed_when: false
  check_mode: no
  register: vrouter_docker_name

- name: Copy vrouter-port-control
  become: yes
  shell: |
    docker cp {{ vrouter_docker_name.stdout }}:/usr/bin/vrouter-port-control /usr/bin/

- name: Install contrail-nova-vif-driver
  become: yes
  pip:
    name:
      - openstacksdk
      - docker-compose
      - dogpile.cache
      - pyasn1-modules
      - networkx
      - requests
      - decorator
      - PyYAML
      - ipaddress
      - numpy
      - git+https://github.com/Juniper/contrail-controller.git#subdirectory=src/vnsw/contrail-vrouter-api/
      - git+https://github.com/tungstenfabric/tf-nova-vif-driver.git
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
