---
- name: Update all apt repo and cache
  become: yes
  apt: update_cache=yes force_apt_get=yes
  register: update_kernel

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Reboot the machine
  become: yes
  reboot:
  when: update_kernel.changed
  register: reboot_machine
